### ISSUE TITLE
Needs corrections after username change (docs link out of date, repo link in docs out of date)

### ISSUE THREAD

**Issue by Corecii** [Frelerik/llama#18]
All links to documentation link to https://frelerik.github.io/llama/ but documentation is now at https://freddylist.github.io/llama/ .

Additionally, I noticed the link in the docs to the repo links to https://github.com/Frelerik/llama/ . Luckily, this still works due to Github's automatic redirect, but it should be changed to https://github.com/freddylist/llama .

**Comment by freddylist** [comment]
Fixed in #17
