### ISSUE TITLE
Missing t?

### ISSUE THREAD

**Issue by tapiov** [Frelerik/llama#8]
Probably PEBCAK but I copied the src and renamed it to Llama. Upon start I got :

  18:16:42.032  [18:16:42] [Store] [INFO] Global store is ready  -  Server - Logger:15
  18:16:42.033  t is not a valid member of ModuleScript "ReplicatedStorage.Libraries.Llama"  -  Server - copy:4
  18:16:42.033  Stack Begin  -  Studio
  18:16:42.034  Script 'ReplicatedStorage.Libraries.Llama.Dictionary.copy', Line 4  -  Studio - copy:4
  18:16:42.034  Stack End  -  Studio
  18:16:42.034  Requested module experienced an error while loading  -  Server - Dictionary:2
  18:16:42.035  Stack Begin  -  Studio
  18:16:42.035  Script 'ReplicatedStorage.Libraries.Llama.Dictionary', Line 2  -  Studio - Dictionary:2
  18:16:42.035  Stack End  -  Studio
  18:16:42.035  Requested module experienced an error while loading  -  Server - Llama:2
  18:16:42.035  Stack Begin  -  Studio
  18:16:42.036  Script 'ReplicatedStorage.Libraries.Llama', Line 2  -  Studio - Llama:2
  18:16:42.036  Stack End  -  Studio
  18:16:42.036  Requested module experienced an error while loading  -  Server - PlayerManager:16
  18:16:42.036  Stack Begin  -  Studio
  18:16:42.037  Script 'ServerStorage.ModuleScripts.PlayerManager', Line 16  -  Studio - PlayerManager:16
  18:16:42.037  Stack End  -  Studio

I found the type t under modules but should I copy that as well?

**Comment by freddylist** [comment]
Yea, Llama expects t to be under the Llama module. That's my bad though, I didn't put that in the guide! I will do that now.
